### ISSUE TITLE
HELP: how to call a MailGun API with your plugin ?

### ISSUE THREAD

**Issue by nk-nareshkumar** [riesenia/cakephp-rabbitmq#3]
Hi There,

Thank you for the plugin.
my requirement little bit different.. 
I am not sending email with thorough my server , i am using mailgun api to send my email.
so how i can call my own controller/method with your plugin which have mailgun api calls ?

Thanks
Naresh Kumar

**Comment by segy** [comment]
Hi

I think having all the logic for this task in controller method is not the good way... you should refactor the code a little bit and then call a shell task using `cake_command` for instance.
